version: '3'

services:

  webapp:
    image: webapp:latest
    container_name: webapp
    ports:
      - 3000:3000
    depends_on:
      - api
    build:
      context: ./webapp
      dockerfile: dockerfile
    volumes:
      - ./webapp:/webapp
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=article
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks: 
      - app_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: api:latest
    container_name: api
    ports:
      - 4000:4000
    build:
      context: ./api
      dockerfile: dockerfile
    volumes:
      - ./api:/api
    networks:
      - app_network
    depends_on:
      - mysql

networks:
  app_network:
    driver: bridge
