services:

  webapp:
    image: webapp:latest
    container_name: webapp
    ports:
      - 3000:3000
    depends_on:
      - api
    build:
      context: ./webapp
      dockerfile: dockerfile
    volumes:
      - ./webapp:/webapp
    networks:
      - app_network

  api:
    image: api:latest
    container_name: api
    ports:
      - 8000:8000
    build:
      context: ./api
      dockerfile: dockerfile
    volumes:
      - ./api:/api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
