
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for article
-- ----------------------------
DROP TABLE IF EXISTS `article`;
CREATE TABLE `article`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(127) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `author` varchar(127) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `numberOfViews` int(11) NOT NULL DEFAULT 0,
  `content` text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `description` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `thumbnail` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 4 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of article
-- ----------------------------
INSERT INTO `article` VALUES (1, 'Sample blog post', 'Olivier', 0, '# Sample blog post\r\n\r\n_April 1, 2020 by [Olivier](/)_\r\n\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\nAenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.\r\nSed posuere consectetur est at lobortis. Cras mattis consectetur purus sit amet fermentum.\r\n\r\nCurabitur blandit tempus porttitor. **Nullam quis risus eget urna mollis** ornare vel eu leo.\r\nNullam id dolor id nibh ultricies vehicula ut id elit.\r\n\r\nEtiam porta sem malesuada magna mollis euismod. Cras mattis consectetur purus sit amet fermentum.\r\nAenean lacinia bibendum nulla sed consectetur.\r\n\r\n## Heading\r\n\r\nVivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.\r\nDuis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.\r\nMorbi leo risus, porta ac consectetur ac, vestibulum at eros.\r\n\r\n### Sub-heading 1\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n\r\n### Sub-heading 2\r\n\r\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\nAenean lacinia bibendum nulla sed consectetur. Etiam porta sem malesuada magna mollis euismod.\r\nFusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo\r\nsit amet risus.\r\n\r\n- Praesent commodo cursus magna, vel scelerisque nisl consectetur et.\r\n- Donec id elit non mi porta gravida at eget metus.\r\n- Nulla vitae elit libero, a pharetra augue.\r\n\r\nDonec ullamcorper nulla non metus auctor fringilla. Nulla vitae elit libero, a pharetra augue.\r\n\r\n1. Vestibulum id ligula porta felis euismod semper.\r\n1. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\r\n1. Maecenas sed diam eget risus varius blandit sit amet non magna.\r\n\r\nCras mattis consectetur purus sit amet fermentum. Sed posuere consectetur est at lobortis.', 'Lacus dapibus ridiculus habitasse lectus quam integer hime\r\nDui aliquam tristique egestas done', 'https://picsum.photos/id/237/200/300');
INSERT INTO `article` VALUES (2, 'Lacus dapibus ridiculus habitasse lectus quam integer hime', 'John', 0, '# Lacus dapibus ridiculus habitasse lectus quam integer hime\r\n\r\nLorem ipsum dolor sit amet consectetur adipiscing elit a phasellus tortor facilisis fermentum proin pretium, torquent nam hac semper egestas vehicula inceptos feugiat eget varius lobortis augue. Porta aliquet proin pretium vivamus risus tellus convallis suscipit, platea odio libero lacinia semper fusce quisque habitasse, ultricies non augue netus curae taciti laoreet. Sociosqu penatibus etiam taciti cum felis morbi convallis tincidunt iaculis suscipit, faucibus imperdiet egestas vehicula ligula odio eros porta cras. \r\n\r\nFermentum dapibus sapien quis lectus suspendisse aliquet convallis massa, maecenas aliquam consequat scelerisque hac dignissim elementum cubilia euismod, ultrices condimentum eleifend dui eget vel quam. Ac leo est purus rhoncus libero dapibus lacus curae duis torquent, at semper sem ullamcorper bibendum posuere hac id. Auctor non iaculis volutpat sapien cursus potenti ac at, mi parturient luctus congue accumsan porttitor ornare mollis porta, taciti placerat donec faucibus lectus torquent curae. \r\n\r\n## Dui aliquam tristique egestas done\r\n\r\n- Tortor commodo euismod arcu posuere, turpis natoque.\r\n\r\n- Sem semper condimentum torquent eleifend rutrum, nullam sodales molestie aliquam.\r\n\r\n- Nulla porttitor cursus diam, non placerat urna nibh, hac praesent.\r\n\r\n- Gravida elementum porta vehicula magnis nec, lobortis facilisi magna netus.\r\n\r\nPorta eleifend mus lobortis venenatis scelerisque euismod, porttitor tempor montes blandit dictumst, dis nibh vehicula tempus luctus. \r\n\r\nLeo sodales taciti ullamcorper tempor curae tincidunt bibendum eget scelerisque venenatis molestie pretium, augue blandit consequat non lectus cras vehicula per egestas ac ridiculus. Ad torquent senectus turpis interdum cras euismod at consequat eros, curae himenaeos class nullam fames luctus sem ultricies, cum venenatis conubia viverra donec vehicula nisl taciti. ', 'Lorem ipsum dolor sit amet', 'https://picsum.photos/id/217/200/300');
INSERT INTO `article` VALUES (3, 'Urna sagittis sodales facilisis ante augue tellus integer nasce', 'Teresa', 0, '# Urna sagittis sodales facilisis ante augue tellus integer nasce\r\n\r\nLorem ipsum dolor sit amet consectetur adipiscing elit curae mattis leo senectus, litora lobortis quisque risus tincidunt fermentum hac porttitor dapibus primis tellus, tristique cursus ante nisi at id morbi montes maecenas elementum. Dis ornare per lobortis sollicitudin rutrum dignissim ad imperdiet eget, nascetur penatibus pharetra parturient justo dui class pellentesque malesuada, nam sodales rhoncus vulputate primis euismod hendrerit duis. Fermentum viverra tristique metus urna quis nisi felis nostra class habitant, faucibus imperdiet dignissim litora velit tincidunt sapien primis accumsan, pretium purus scelerisque a habitasse id eleifend nulla ultricies. \r\n\r\nOdio neque turpis nam augue laoreet cursus varius faucibus, ligula convallis congue est vitae proin aenean molestie, integer himenaeos tincidunt lacus dis natoque quam. Quam sem dis posuere venenatis tortor euismod cras vehicula, vitae inceptos sociosqu platea per quis pulvinar viverra accumsan, laoreet fames congue et massa cursus nisi. \r\n\r\n## Venenatis fringilla aenean nascetur\r\n\r\n- Pharetra aenean interdum ullamcorper fusce in, neque magna sagittis.\r\n\r\n- Pellentesque blandit lobortis magnis condimentum ultrices, urna sociis tincidunt.\r\n\r\n- Pulvinar ad lectus massa ligula, taciti velit risus.\r\n\r\n- Metus odio aliquam facilisis praesent, nostra id etiam.\r\n\r\nEst facilisis auctor nec mauris cubilia praesent augue tempor tempus, dictum quam maecenas potenti pharetra ridiculus libero et congue orci, natoque tincidunt mollis integer velit taciti neque vulputate. \r\n\r\nMagnis nunc viverra elementum tristique felis vehicula, tortor morbi laoreet sed phasellus dictumst, cubilia fames augue sodales ultrices. Accumsan tempor primis in venenatis massa mi posuere sollicitudin, taciti pulvinar tellus facilisi quam gravida aenean. Luctus bibendum pellentesque fusce at felis non orci blandit turpis, per ante eros velit hac sollicitudin nec urna dui, purus suscipit dictumst mauris ornare mattis maecenas vulputate. ', 'Venenatis fringilla aenean nascetur', 'https://picsum.photos/id/233/200/300');

SET FOREIGN_KEY_CHECKS = 1;
